apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: myrecipebooknamespace
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
        ports:
        - containerPort:  5672
          name: rabbitmq
        - containerPort:  15672
          name: rabbitmq-adm
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name:  rabbitmq
  namespace: myrecipebooknamespace
spec:
  selector:
    app: rabbitmq
  type: LoadBalancer
  ports:
  - name:  rabbitmq-port
    port:  5672
    targetPort:  5672
  - name:  rabbitmq-port-adm
    port:  15672
    targetPort:  15672