
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlserver-pv
  namespace: myrecipebooknamespace
  labels:
    type: local-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /app/meuvolume
  storageClassName: manual

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pvc
  namespace: myrecipebooknamespace
  labels:
    app: sqlserver
spec:
  storageClassName: manual #rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local-pv

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  sqlserver
  namespace: myrecipebooknamespace
  labels:
    app:  sqlserver
spec:
  selector:
    matchLabels:
      app: sqlserver
  replicas: 1
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
        - name: MSSQL_PID
          value: Developer
        - name: MSSQL_SA_PASSWORD
          value: password123!
        - name: ACCEPT_EULA
          value: "Y"
        ports:
        - containerPort:  1433
          name:  sqlserver
        volumeMounts:
        - name: db-data
          mountPath: /var/opt/mssql/data
      volumes:
        - name: db-data
          emptyDir: {}
        # - name: db-data-storage-pvc
        #   PersistentVolumeClaim:
        #     claimName: sqlserver-pvc

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: sqlserver
  name:  sqlserver
  namespace: myrecipebooknamespace
spec:
  selector:
    app: sqlserver
  type: LoadBalancer
  ports:
  - name:  sqlserver-port
    protocol: TCP
    port:  1433
    targetPort:  1433
