//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecipeBook.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyRecipeBook.Exceptions.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido ingredientes duplicado..
        /// </summary>
        public static string Duplicated_Ingredients_In_List {
            get {
                return ResourceManager.GetString("Duplicated_Ingredients_In_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email já cadastrado..
        /// </summary>
        public static string Email_Already_Registered {
            get {
                return ResourceManager.GetString("Email_Already_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email não pode estar vazio..
        /// </summary>
        public static string Email_Empty {
            get {
                return ResourceManager.GetString("Email_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail e/ ou senha inválidos..
        /// </summary>
        public static string Email_Or_Password_invalid {
            get {
                return ResourceManager.GetString("Email_Or_Password_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient não pode estar vazio..
        /// </summary>
        public static string Ingredient_Empty {
            get {
                return ResourceManager.GetString("Ingredient_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredienets fora do padrão..
        /// </summary>
        public static string Ingredient_Not_Following_Pattern {
            get {
                return ResourceManager.GetString("Ingredient_Not_Following_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de ingredientes não é permitido..
        /// </summary>
        public static string Invalid_Number_Ingredients {
            get {
                return ResourceManager.GetString("Invalid_Number_Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password esta invalido..
        /// </summary>
        public static string Invalid_Password {
            get {
                return ResourceManager.GetString("Invalid_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode estar vazio..
        /// </summary>
        public static string Name_Empty {
            get {
                return ResourceManager.GetString("Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de autenticação não esta sendo enviado..
        /// </summary>
        public static string No_Token {
            get {
                return ResourceManager.GetString("No_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente imagens (PNG, JPG, JPEG) são aceitas..
        /// </summary>
        public static string ONLY_IMAGES_ACCEPTED {
            get {
                return ResourceManager.GetString("ONLY_IMAGES_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password diferente do cadastrado atualmente..
        /// </summary>
        public static string Password_Different_Current_Password {
            get {
                return ResourceManager.GetString("Password_Different_Current_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password não pode ser vazio..
        /// </summary>
        public static string Password_Empty {
            get {
                return ResourceManager.GetString("Password_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receita não pode encontrada..
        /// </summary>
        public static string Recipe_Not_Found {
            get {
                return ResourceManager.GetString("Recipe_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título não pode ser vazio..
        /// </summary>
        public static string Recipe_Title_Empty {
            get {
                return ResourceManager.GetString("Recipe_Title_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Token esta expirado..
        /// </summary>
        public static string REFRESH_TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido..
        /// </summary>
        public static string Unknow_Error {
            get {
                return ResourceManager.GetString("Unknow_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não possui permissão para o recurso..
        /// </summary>
        public static string User_Without_Permission_Access_Resource {
            get {
                return ResourceManager.GetString("User_Without_Permission_Access_Resource", resourceCulture);
            }
        }
    }
}
